# Generated by Django 5.1.2 on 2024-11-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadenainformacion',
            name='rango_fecha_fin',
            field=models.DateField(default='2024-11-13'),
        ),
        migrations.AlterField(
            model_name='cadenainformacion',
            name='rango_fecha_inicio',
            field=models.DateField(default='2024-11-13'),
        ),
        migrations.AlterField(
            model_name='visitainventario',
            name='fecha_visita_actual',
            field=models.DateField(blank=True, default='2024-11-13', null=True),
        ),
        migrations.AlterField(
            model_name='visitainventario',
            name='semana',
            field=models.CharField(default='', max_length=9),
        ),
    ]
