# Generated by Django 5.1.2 on 2024-11-03 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadenainformacion',
            name='rango_fecha_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cadenainformacion',
            name='rango_fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
