# Generated by Django 5.1.2 on 2024-11-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitainventario',
            name='inventario_inicial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitainventario',
            name='temporada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
