# Generated by Django 5.1.2 on 2024-11-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0002_alter_visitainventario_inventario_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitainventario',
            name='venta_real',
            field=models.TextField(default='[0,0,0,0,0]'),
        ),
    ]
