# Generated by Django 5.1.2 on 2024-11-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0002_alter_cadenainformacion_rango_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendadetalle',
            name='horario_cierre_bodega',
            field=models.CharField(choices=[('11-12', '11-12'), ('12-13', '12-13')]),
        ),
    ]
