# Generated by Django 5.1.2 on 2024-11-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0003_visitainventario_venta_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendadetalle',
            name='correo',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tiendadetalle',
            name='direccion',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='tiendadetalle',
            name='telefono',
            field=models.CharField(default='', max_length=9),
        ),
    ]
