# Generated by Django 5.1.2 on 2024-11-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0003_alter_tiendadetalle_horario_cierre_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productodetalle',
            name='iva',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='productodetalle',
            name='valor_con_iva',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='productodetalle',
            name='valor_sin_iva',
            field=models.FloatField(),
        ),
    ]
