# Generated by Django 5.1.2 on 2024-11-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0004_alter_productodetalle_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productodetalle',
            name='iva',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productodetalle',
            name='valor_con_iva',
            field=models.FloatField(),
        ),
    ]
